version: '2'

services:
  demo:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "6800:6800"
      - "6080:6080"
      - "6081:6081"
    environment:
      - TERM=linux
    command: bash -c "cd auto && scrapyd"
